# **Introduction to Tensors and Variables**

**Learning objectives**

1. Understand basic and advanced `tensor` concepts
2. Understand single-axis and multi-axis indexing
3. Create `tensors` and `Variables`

## **Introduction**

In this notebook, we look at tensors, which are multi-dimensional arrays with a uniform type (called a `dtype`). Tensors are (kind of) like `np.arrays`. All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

We also look at variables, a `tf.Variable` represents a tensor whose value can be changed by running operations (ops) on it. Specific ops allow you to read and modify the value of this tensor. Higher level libraries like `tf.keras` use `tf.Variable` to store model parameters.

## **Load necessary libraries**

Import necessary libraries

In [1]:
import tensorflow as tf
import numpy as np

print("TensorFlow version:", tf.version.VERSION)

TensorFlow version: 2.4.1


## **Basic and advanced tensor concepts**

### **Basics**

Let's create some basic tensors. 

#### **Tensor objects**
A **scalar** is a rank-0 tensor. A scalar contains a single value, and no *axes*

In [2]:
# A scalar tensor contains a single value and no axes
rank_0_tensor = tf.constant(4)
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

A **vector** is a rank-1 tensor. A vector is like a list of values, it has 1 axis

In [3]:
# A vector tensor has 1 axis
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
rank_1_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

A **matrix** is a rank-2 tensor. It has 2 axes.

In [4]:
# A matrix tensor has 2 axes
# dtype can be specified at creation
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

<center><img src="img/tensors.png" width=500 height=500></center>

Tensors may have more axes, here is a tensor with 3 axes

In [25]:
# There can be an arbitrary number of axes
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

rank_3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

Tensors with more than 2 axes can be visualised in many ways

<center><img src="img/multi-tensors.png" width=600 height=600></center>

A tensor can be converted to a NumPy array either using `np.array` or the `tensor.numpy` method.

In [9]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [11]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

Tensors often contain `float` and `int` types, but may have many other types, including:
- complex numbers
- strings

The base `tf.Tensor` class requires tensors to be *rectangular* - that is, **along each axis, every element must be the same size**. However, some specialised types of tensors can handle different shapes:
- ragged tensors
- sparse tensors

#### **Basic math**

Basic math can be performed on tensors, including addition, element-wise multiplication, and matrix multiplication.

In [12]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

**Addition**

In [13]:
print(tf.add(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [16]:
print(a + b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


**Element-wise multiplication**

In [14]:
print(tf.multiply(a, b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [17]:
print(a * b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


**Matrix multiplication**

In [15]:
print(tf.matmul(a, b))

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [18]:
print(a @ b)

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


**Tensor ops**

In [24]:
c = tf.constant([[4.0, 5.0], 
                 [10.0, 1.0]])

# Find the largest value
tf.reduce_max(c)

# Find the INDEX of the largest value
tf.argmax(c)

# Compute the softmax
tf.nn.softmax(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>

### **Tensor shapes**

Tensors have shapes. Some vocabulary:
- **Shape** - Tuple storing the length of each of the dimensions of a tensor
- **Rank** - Number of tensor dimensions. A **scalar** is rank-0, a **vector** is rank-1, a **matrix** is rank-2
- **Axis** or **Dimension** - Lowest structure level of a tensor
- **Size** - Total number of the items in a tensor, its product shape vector

Tensors and `tf.TensorShape` objects have convenient properties for accessing these.

Note: although there may be references to *tensors of 2 dimensions*, a rank-2 tensor usually does not describe a 2D space.

In [34]:
# `tf.zeros` creates a tensor with all elements set to 0
rank_4_tensor = tf.zeros([3, 2, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

<center><img src="img/rank-4-tensor.png" width=500 height=500><\center>

In [29]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5):", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5): 120


While axes are often referred to by their indices, you should always keep track of the meaning of each. **Axes are ordered from global to local**: 
1. **batch** axis
2. **spatial** axes
3. **features** for each location

This way feature vectors are contiguous regions of memory.

<center><img src="img/tf-axes.png" width=300 height=300><\center>

## **Single-axis and multi-axis indexing**

### **Single-axis indexing**

TensorFlow follows standard Python and NumPy indexing rules:

- indexes start at `0`
- negative indices count backwards from the end
- colons `:` are used for slicing as `start:stop:step`

In [33]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
rank_1_tensor.numpy()

array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34], dtype=int32)

Indexing with a scalar **removes the dimension**

In [35]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 34


Indexing with a slice `:` **keeps the dimension**

In [39]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4: ", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4:  [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [43]:
"karine alla en irak"[::-1].replace(" ","") == "karine alla en irak"

False

In [41]:
"karine alla en irak"[::-1]

'kari ne alla enirak'