# **Getting started with TensorFlow (Eager execution mode)**

**Learning objectives**

- Understand the differences between TensorFlow two execution modes: **eager execution** and **graph execution**
- Practice defining and performing basic operations on constant `tensors`
- Use TensorFlow automatic differentiation capability

## **Introduction**

**Eager execution**

Eager mode evaluates operations immediately and returns concrete values immediately. To enable eager mode simple place `tf.enable_eager_execution()` at the top of the code. It is recommended to use eager execution when prototyping as it is intuitive, easier to debug, and requires less boilerplate code.

**Graph execution**

Graph mode (aka delayed execution mode) is TensorFlow default execution mode (although this will change to eager with `TF 2.0`). In graph mode operations only produce a symbolic graph which doesn't get executed until run within the context of a `tf.Session()`. This style of coding is less intuitive and has more boilerplate, however it can lead to performance optimisations and is particularly suited for distributing training across multiple devices. It is recommended to use delayed execution for performance sensitive production code.

In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


## **Eager execution**

This mode is set by default on TensorFlow 2.x

### **Adding two tensors**

The value of a tensor, as well as its shape and data type are printed

In [2]:
a = tf.constant(value=[5, 3, 8], dtype=tf.int32)
b = tf.constant(value=[3, -1, 2], dtype=tf.int32)
c = tf.add(x=a, y=b)
print(c)

tf.Tensor([ 8  2 10], shape=(3,), dtype=int32)


**Overloaded operators**

We can also perform a `tf.add()` using the `+` operator. The `/, -, *` and `**` operators are similarly overloaded with the appropriate tensorflow operation.

In [3]:
c = a + b
print(c)

tf.Tensor([ 8  2 10], shape=(3,), dtype=int32)


### **NumPy interoperability**

In addition to native TF tensors, tensorflow operations can take native python types and NumPy arrays as operands.

In [4]:
import numpy as np

a_py = [1, 2] # native Python list
b_py = [3, 4] # native Python list

a_np = np.array([1, 2]) # NumPy array
b_np = np.array([3, 4]) # NumPy array

a_tf = tf.constant(value=[1, 2], dtype=tf.int32) # native TensorFlow tensor
b_tf = tf.constant(value=[3, 4], dtype=tf.int32) # native TensorFlow tensor

for result in [tf.add(x=a_py, y=b_py), tf.add(x=a_np, y=b_np), tf.add(x=a_tf, y=b_tf)]:
    print("Type: {}, Value: {}".format(type(result), result))

Type: <class 'tensorflow.python.framework.ops.EagerTensor'>, Value: [4 6]
Type: <class 'tensorflow.python.framework.ops.EagerTensor'>, Value: [4 6]
Type: <class 'tensorflow.python.framework.ops.EagerTensor'>, Value: [4 6]


A native TensorFlow tensor can be converted to a NumPy array using `.numpy()`.

In [7]:
a_tf.numpy()

array([1, 2], dtype=int32)

## **Linear Regression**

Now let's use low level tensorflow operations to implement linear regression.

### **Toy data set**

We'll model the following function:

$$
y = 2x + 10
$$

In [19]:
X = tf.constant(value=np.arange(11), dtype=tf.float32)
Y = 2*X + 10
print("X: {}".format(X))
print("Y: {}".format(Y))

X: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Y: [10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


### **Loss function**

Using mean squared error, the loss function is:

$$
\Sum
$$